### ISSUE TITLE
Have range upgradeable

### ISSUE THREAD

**Issue by carstorm** [bl4ckscor3/The-Plopper#1]
I like that the range is configurable but it would be nice if this could be upgraded in game using an item.

**Comment by bl4ckscor3** [comment]
You mean similar to Thermal Expansion's augments? I'm not sure if I want something like that, but I'll definetly think about a possible implementation.

**Comment by carstorm** [comment]
Not necessarily using that method although that could be one way. It could also use enderio's method (one upgrade slot with the upgrade used determining how much the range increases by) or some other method completely.

**Comment by bl4ckscor3** [comment]
Sorry, I forgot I had part of the code already laid out locally for a while. I implemented the range upgrade and a new version will come out today/tomorrow. Minimum range is now 2 (white), maximum 16 (black). The config option has been removed.

https://i.imgur.com/yS5fMXk.png
