### ISSUE TITLE
Plopper runs into issues causing FML Spam (1.12.2)

### ISSUE THREAD

**Issue by DatrixTHLK** [bl4ckscor3/The-Plopper#2]
Hi,
I'm having issues with the Plopper it seems to run into issues every so often with VanillaFix installed. It doesn't crash me to the main menu screen or crashes to desktop. Just causes spam and crash errors and these are two of them. It does this while I'm near them or when I come back from a long distance away and the chunk loads back up.

Minecraft: 1.12.2
Forge: 14.23.5.2825
Theplopper: 1.12.x - v1.1

Crash log 1: https://gist.github.com/DatrixTHLK/1fe23ce3644a1c405f7f5cf8d0cddfdd
Crash log 2: https://gist.github.com/DatrixTHLK/b2d56c706f288be1e1c5405024ac855e

**Comment by bl4ckscor3** [comment]
I have no idea what exactly causes this crash, but I uploaded a fixed version nonetheless.

**Comment by DatrixTHLK** [comment]
Thanks for the update and response. I appreciate it.
